💄 feat: design system Tabs(Tabs, TabBtn, TabShowMore) migration
waktaplay/ui pull request #10
Opened 2024-07-04 00:31 UTC by MERx88

### Tabs 추가 완료

사용법은 주석으로 달아 놓았지만 한번더 남겨놓겠습니다.

❗️ 우선 기능을 더하다 보니 useState로 컨텐츠 바꾸는 부분이 들어가서 재사용성과 가독성이 조금 떨어집니다 이점 양해 부탁드립니다 이게 최선인거 같은데 혹시 더좋은 방법이 있다면 코멘트 남겨주세요!

**tabs 사용법**

✅ props 는 TABS 와 CHIPS 가 있습니다. 원하는 tab 이름과 원하는 chip들을 삽입가능 합니다.
✅ uint은 임시로 넣어둔 것이니 원하는 컨텐츠를 넣어 사용하시면 됩니다 
✅ const [selectedTabIndex, setSelectedTabIndex] = useState(0) 해당 useState를 꼭 사용해주세요 

**tabshowmore 사용법**

 ✅ const [isShowedMore, setIsShowedMore] = useState(false) 해당 useState를 꼭 함께 사용해주세요
 
 더 자세한 사항은 주석에서 확인 가능합니다.

 ❗️❗️❗️❗️❗️❗️매우 중요 ❗️❗️❗️❗️❗️❗️

main 에서는 useState를 사용할수 없어서 App.tsx 파일을 추가했습니다 다른 ui 컴포넌트도 다 옮겨 놨습니다! 

확인해보시다가 문제있으면 말씀 부탁드립니다!

2024-07-04 13:41 UTC, kms0219kms requested changes

2024-07-04 13:41 UTC, kms0219kms commented on src/components/Tabs/elements/TabBtn.tsx
> +  font-family: Pretendard;
Pretendard -> Wanted Sans 변경 필요. 이미 글로벌에 선언되어있으므로 삭제하시면 될 것 같습니다.

2024-07-04 13:41 UTC, kms0219kms commented on src/components/Tabs/elements/TabShowMore.tsx
> +  font-family: Pretendard;
상동 (Pretendard -> Wanted Sans)

2024-07-04 13:41 UTC, kms0219kms commented on src/components/Tabs/index.tsx
> +  display: flex;
Gap 16px 누락

2024-07-06 02:33 UTC, MERx88 commented on src/components/Tabs/index.tsx
> +  display: flex;
이 부분 gap이 필요 없을거 같아서 추가를 안했는데 필요할까요? 
![스크린샷 2024-07-06 오전 11 32 35](https://github.com/waktaplay/ui/assets/117734307/f41a9427-30cd-4565-a93b-8da15ef2d66b)

2024-07-06 02:35 UTC, MERx88 commented on src/components/Tabs/index.tsx
> +  display: flex;
![스크린샷 2024-07-06 오전 11 34 32](https://github.com/waktaplay/ui/assets/117734307/77106d5d-91db-49dd-86c5-08c84368b5ed)

요렇게 두개 필터 들어갔을때  gap 설정하는거라서요!

2024-07-06 03:26 UTC, kms0219kms commented on src/components/Tabs/index.tsx
> +  display: flex;
피그마 보시면, 필터와 필터 사이에 16픽셀 정도 gap이 들어있습니다! 디자이너분이랑 다시한번 더블체크는 해볼께요.

2024-07-07 03:18 UTC, MERx88 commented on src/components/Tabs/index.tsx
> +  display: flex;
넵 gap 추가했습니다! 확인해주세용

2024-07-07 10:29 UTC, kms0219kms approved these changes
LGTM. Squash Merge

2024-07-07 10:29 UTC, merged