Feature/artist circle
waktaplay/ui pull request #34
Opened 2024-08-13 15:24 UTC by East-cloud-of-forest

Circle 컴포넌트 하나뿐 이지만 확장성을 고려해 Artist 컴포넌트 하위 오브젝트로 넣어놨습니다.

**props**
artistId
checked

2024-08-28 13:21 UTC, kms0219kms requested changes
프로필이미지 svg로 넣으셨던데, Raw파일을 보니 그냥 png라서 svg로 넣을 필요가 없어보이구요.
추후 확장성을 고려해서 img태그로 빼면서 src를 props로 받는게 좋을 것 같습니다.

어쩌면 artistData 자체를, Array가 아닌 Object로 props에서 끌고와도 될거같아요.

2024-08-31 05:02 UTC, East-cloud-of-forest commented
enum 이었던 artist 정보를 props 로 바꿨습니다.

**props**
src
label
backgroundColor
checked

* App 파일에서는 임시로 넣을 이미지를 에셋 폴더에 저장 하기는 좀 그래서 나무위키 이미지로 넣어두었습니다.

2024-08-31 05:03 UTC, kms0219kms commented
@East-cloud-of-forest conflict가 있는거 같은데, resolve 부탁드릴게요~

2024-08-31 07:23 UTC, kms0219kms approved these changes
LGTM

2024-08-31 07:24 UTC, merged